# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('contents', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435',
                'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435',
            },
        ),
        migrations.CreateModel(
            name='FooterBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('contents', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440 \u0432 \u043f\u043e\u0434\u0432\u0430\u043b\u0435',
                'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b \u0432 \u043f\u043e\u0434\u0432\u0430\u043b\u0435',
            },
        ),
    ]
