# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20160518_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerbanner',
            name='photo',
        ),
        migrations.AddField(
            model_name='footerbanner',
            name='link_title',
            field=models.CharField(max_length=255, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xbd\xd0\xb0 \xd0\xba\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xba\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='link',
            field=models.CharField(default=b'/page-aktsii-i-skidki', max_length=255, verbose_name=b'\xd0\xa1\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0'),
        ),
    ]
