# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20160520_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerbanner',
            name='text',
        ),
    ]
