# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import stonegarant.models.attached_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba')),
                ('photo', models.FileField(blank=True, null=True, upload_to=stonegarant.models.attached_image.upload_path_handler, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u043d\u044b\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Cvetnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('length', models.BigIntegerField(default=0, verbose_name=b'\xd0\x94\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('width', models.BigIntegerField(default=0, verbose_name=b'\xd0\xa8\xd0\xb8\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('height', models.BigIntegerField(default=0, verbose_name=b'\xd0\x92\xd1\x8b\xd1\x81\xd0\xbe\xd1\x82\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('added_value', models.BigIntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb4\xd0\xb1\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xba \xd0\xb1\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9 \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb5')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0446\u0432\u0435\u0442\u043d\u0438\u043a\u0430',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0446\u0432\u0435\u0442\u043d\u0438\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Granit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0433\u0440\u0430\u043d\u0438\u0442\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0433\u0440\u0430\u043d\u0438\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_result', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xb7\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb0\xd1\x82 \xd1\x80\xd0\xb0\xd1\x81\xd1\x81\xd1\x87\xd1\x91\xd1\x82\xd0\xbe\xd0\xb2')),
                ('user_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f, \xd0\xb8\xd0\xbc\xd1\x8f')),
                ('user_comment', models.TextField(blank=True, max_length=150, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb9 \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8f')),
                ('status', models.CharField(choices=[(b'N', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), (b'S', b'\xd0\x9e\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd'), (b'D', b'\xd0\x94\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb2\xd0\xbd\xd0\xb5\xd1\x81\xd0\xb5\xd0\xbd\xd1\x8b'), (b'P', b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb8\xd0\xb7\xd0\xb2\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'), (b'C', b'\xd0\x97\xd0\xb0\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb5\xd1\x88\xd0\xb5\xd0\xbd'), (b'R', b'\xd0\x94\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd')], default=b'N', max_length=1)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2016, 5, 13, 21, 57, 41, 873550), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('user_email', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Email')),
                ('total_price', models.BigIntegerField(blank=True, null=True, verbose_name=b'\xd0\x98\xd1\x82\xd0\xbe\xd0\xb3\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0')),
                ('notes', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('order_number', models.CharField(max_length=150, unique=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0')),
                ('order_pin', models.CharField(max_length=150, verbose_name=b'\xd0\x9f\xd0\x98\xd0\x9d-\xd0\xba\xd0\xbe\xd0\xb4')),
                ('cvetnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Cvetnik', verbose_name=b'\xd0\xa6\xd0\xb2\xd0\xb5\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='Podstavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf')),
                ('length', models.BigIntegerField(default=0, verbose_name=b'\xd0\x94\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('width', models.BigIntegerField(default=0, verbose_name=b'\xd0\xa8\xd0\xb8\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('height', models.BigIntegerField(default=0, verbose_name=b'\xd0\x92\xd1\x8b\xd1\x81\xd0\xbe\xd1\x82\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('added_value', models.BigIntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb4\xd0\xb1\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xba \xd0\xb1\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9 \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb5')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u043f\u043e\u0434\u0441\u0442\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u043f\u043e\u0434\u0441\u0442\u0430\u0432\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='Polirovka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf')),
                ('added_value', models.BigIntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb4\xd0\xb1\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xba \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb5 \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd0\xbb\xd0\xb5\xd0\xba\xd1\x82\xd0\xb0 (%)')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u043f\u043e\u043b\u0438\u0440\u043e\u0432\u043a\u0438',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u043f\u043e\u043b\u0438\u0440\u043e\u0432\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='ReadyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'uploads/ready', verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('admin_thumb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '\u0413\u043e\u0442\u043e\u0432\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u0413\u043e\u0442\u043e\u0432\u044b\u0435 \u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb7\xd1\x8b\xd0\xb2')),
                ('person', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa7\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xba')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='SeoArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
            ],
            options={
                'verbose_name': 'SEO \u0441\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': 'SEO \u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='SeoEmpoweredModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'SEO-\xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('meta_title', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'META title')),
            ],
        ),
        migrations.CreateModel(
            name='Stella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('length', models.BigIntegerField(default=0, verbose_name=b'\xd0\x94\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('width', models.BigIntegerField(default=0, verbose_name=b'\xd0\xa8\xd0\xb8\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('height', models.BigIntegerField(default=0, verbose_name=b'\xd0\x92\xd1\x8b\xd1\x81\xd0\xbe\xd1\x82\xd0\xb0, \xd1\x81\xd0\xbc')),
                ('added_value', models.BigIntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb4\xd0\xb1\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xba \xd0\xb1\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9 \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb5')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0441\u0442\u0435\u043b\u044b',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0441\u0442\u0435\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('seoempoweredmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stonegarant.SeoEmpoweredModel')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('slug', models.CharField(max_length=255, verbose_name=b'URL')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0440\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0440\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
            bases=('stonegarant.seoempoweredmodel',),
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('seoempoweredmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stonegarant.SeoEmpoweredModel')),
                ('photo1', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'uploads/memorials', verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 1')),
                ('photo2', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'uploads/memorials', verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 2')),
                ('admin_thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.BigIntegerField(unique=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('slug', models.CharField(max_length=255, verbose_name=b'URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('stella', models.CharField(max_length=50, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb5\xd0\xbb\xd0\xb0')),
                ('podstavka', models.CharField(max_length=50, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0')),
                ('cvetnik', models.CharField(max_length=50, verbose_name=b'\xd0\xa6\xd0\xb2\xd0\xb5\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba')),
                ('discount', models.BooleanField(verbose_name=b'\xd0\xa1\xd0\xbe \xd1\x81\xd0\xba\xd0\xb8\xd0\xb4\xd0\xba\xd0\xbe\xd0\xb9')),
                ('discount_percent', models.BigIntegerField(blank=True, null=True, verbose_name=b'\xd0\xa1\xd0\xba\xd0\xb8\xd0\xb4\xd0\xba\xd0\xb0 (\xd0\xbf\xd1\x80\xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd1\x82)')),
                ('discount_price', models.BigIntegerField(blank=True, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd1\x81\xd0\xbe \xd1\x81\xd0\xba\xd0\xb8\xd0\xb4\xd0\xba\xd0\xbe\xd0\xb9')),
                ('base_price', models.BigIntegerField(blank=True, null=True, verbose_name=b'\xd0\x91\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0')),
                ('popularity', models.BigIntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbf\xd1\x83\xd0\xbb\xd1\x8f\xd1\x80\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c')),
                ('categories', models.ManyToManyField(to='stonegarant.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb8')),
                ('granit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Granit', verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x82\xd0\xb0')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043c\u044f\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u041f\u0430\u043c\u044f\u0442\u043d\u0438\u043a\u0438',
            },
            bases=('stonegarant.seoempoweredmodel',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('seoempoweredmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stonegarant.SeoEmpoweredModel')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u0443\u0436\u0435\u0431\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0421\u043b\u0443\u0436\u0435\u0431\u043d\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
            bases=('stonegarant.seoempoweredmodel',),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('seoempoweredmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stonegarant.SeoEmpoweredModel')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('slug', models.CharField(max_length=255, verbose_name=b'URL')),
                ('short', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('show_in_list', models.BooleanField(default=False, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd1\x8f?')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
            bases=('stonegarant.seoempoweredmodel',),
        ),
        migrations.AddField(
            model_name='polirovka',
            name='stella',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='podstavka',
            name='stella',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='order',
            name='podstavka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Podstavka', verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='order',
            name='polirovka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Polirovka', verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='order',
            name='stella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='cvetnik',
            name='stella',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='stella',
            name='memorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stella_variants', to='stonegarant.Memorial', verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xbc\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='seoarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='seoarticle',
            name='memorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Memorial', verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xbc\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='readywork',
            name='memorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Memorial', verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xbc\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='order',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonegarant.Memorial', verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xbc\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='attachedimage',
            name='memorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stonegarant.Memorial', verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xbc\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
    ]
