# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonegarant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='cvetnik',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='podstavka',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='stella',
        ),
        migrations.AlterField(
            model_name='cvetnik',
            name='stella',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvetnik', to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 18, 23, 52, 387838), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='podstavka',
            name='stella',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podstavka', to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='polirovka',
            name='stella',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polirovka', to='stonegarant.Stella', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x8d\xd0\xbb\xd0\xbb\xd0\xb0'),
        ),
    ]
