from reply import *
from seo_model import *
from category import *
from memorial import *
from article import *
from ready_work import *
from service_page import *
from static_page import *
from order import *
from stella import *
from cvetnik import *
from polirovka import *
from podstavka import *
from granit import *